In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('upi.csv')
df

  Financial Year  Volume (in lakhs)
0        2018-19           232602.0
1        2019-20           340025.0
2        2020-21           437445.0

In [3]:
df1 = pd.read_csv('UPI apps transaction.csv')
df1

,UPI Banks,Volume (Mn) By Costumers,Value (Cr) by Costumers,Volume (Mn),Value (Cr),Month,Year
0,Airtel Payments Bank Apps,9.04,2248.49,15.12,5732.09,12,2021
1,Airtel Payments Bank Apps,8.41,1923.95,15.90,5554.63,11,2021
2,Airtel Payments Bank Apps,7.60,1491.34,14.31,4746.79,10,2021
3,Airtel Payments Bank Apps,6.91,1520.92,11.52,3759.12,9,2021
4,Airtel Payments Bank Apps,6.14,1396.65,9.31,2941.88,8,2021
...,...,...,...,...,...,...,...
649,YuvaPay,1.33,60.44,1.33,60.44,6,2021
650,YuvaPay,2.32,73.16,2.32,73.16,5,2021
651,YuvaPay,1.59,51.22,1.59,51.22,4,2021
652,YuvaPay,0.56,18.56,0.56,18.56,3,2021
653,YuvaPay,0.02,0.63,0.02,0.63,2,2021

In [4]:
df1.head(50)

,UPI Banks,Volume (Mn) By Costumers,Value (Cr) by Costumers,Volume (Mn),Value (Cr),Month,Year
0,Airtel Payments Bank Apps,9.04,2248.49,15.12,5732.09,12,2021
1,Airtel Payments Bank Apps,8.41,1923.95,15.90,5554.63,11,2021
2,Airtel Payments Bank Apps,7.60,1491.34,14.31,4746.79,10,2021
3,Airtel Payments Bank Apps,6.91,1520.92,11.52,3759.12,9,2021
4,Airtel Payments Bank Apps,6.14,1396.65,9.31,2941.88,8,2021
5,Airtel Payments Bank Apps,5.79,1534.21,7.36,2342.76,7,2021
6,Airtel Payments Bank Apps,5.06,1323.26,6.69,2821.94,6,2021
7,Airtel Payments Bank Apps,4.06,429.12,4.06,429.12,5,2021
8,Airtel Payments Bank Apps,3.53,363.66,14.70,11172.43,4,2021
9,Airtel Payments Bank Apps,3.79,381.74,3.79,381.74,3,2021
10,Airtel Payments Bank Apps,3.33,348.70,3.33,348.70,2,2021
11,Airtel Payments Bank Apps,3.71,355.77,3.71,355.77,1,2021
12,Allahabad Bank App,0.02,7.43,0.02,7.43,12,2021
13,Allahabad Bank App,0.02,6.28,0.02,6.28,11,2021
14,Allahabad Bank App,0.02,6.35,0.02,6.35,10,2021
15,Allahabad Bank App,0.02,5.34,0.02,5.34,9,2021
16,Allahabad Bank App,0.01,4.44,0.01,4.44,8,2021
17,Allahabad Bank App,0.01,2.03,0.01,2.03,7,2021
18,Allahabad Bank App,0.01,4.43,0.01,4.43,5,2021
19,Allahabad Bank App,0.02,5.21,0.02,5.21,4,2021
20,Allahabad Bank App,0.05,13.51,0.05,13.51,3,2021
21,Allahabad Bank App,0.05,12.23,0.05,12.23,2,2021
22,Allahabad Bank App,0.09,21.14,0.09,21.14,1,2021
23,Amazon Pay,76.18,6641.62,76.18,6641.62,12,2021
24,Amazon Pay,71.04,6041.96,71.04,6041.96,11,2021
25,Amazon Pay,68.82,6286.60,68.82,6286.60,10,2021
26,Amazon Pay,62.90,5267.79,62.90,5267.79,9,2021
27,Amazon Pay,60.67,5297.16,60.67,5297.16,8,2021
28,Amazon Pay,62.83,5223.57,62.83,5223.57,7,2021
29,Amazon Pay,51.34,4814.74,51.34,4814.74,6,2021
30,Amazon Pay,58.35,4782.59,58.35,4782.59,5,2021
31,Amazon Pay,49.12,4272.47,49.12,4272.47,4,2021
32,Amazon Pay,52.38,4457.47,52.38,4457.47,3,2021
33,Amazon Pay,44.22,3831.99,44.22,3831.99,2,2021
34,Amazon Pay,46.30,4044.38,46.30,4044.38,1,2021
35,Andhra Bank App,0.02,13.32,0.02,13.32,1,2021
36,AU Small Finance Bank App,0.21,76.22,0.21,76.22,12,2021
37,AU Small Finance Bank App,0.17,67.04,0.17,67.04,11,2021
38,AU Small Finance Bank App,0.16,62.15,0.16,62.15,10,2021
39,AU Small Finance Bank App,0.13,46.49,0.13,46.49,9,2021
40,AU Small Finance Bank App,0.10,38.53,0.10,38.53,8,2021
41,AU Small Finance Bank App,0.08,33.12,0.08,33.12,7,2021
42,AU Small Finance Bank App,0.05,25.43,0.05,25.43,6,2021
43,AU Small Finance Bank App,0.04,20.29,0.04,20.29,5,2021
44,AU Small Finance Bank App,0.04,20.23,0.04,20.23,4,2021
45,AU Small Finance Bank App,0.04,21.33,0.04,21.33,3,2021
46,AU Small Finance Bank App,0.03,15.48,0.03,15.48,2,2021
47,AU Small Finance Bank App,0.02,12.28,0.02,12.28,1,2021
48,Axis Bank Apps,6.63,916.58,59.85,957.37,12,2021
49,Axis Bank Apps,6.71,875.09,70.83,920.76,11,2021